#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

export PYTHONPATH=/Projectdirname

python /app/manage.py collectstatic --noinput
#python path in docker environment i.e
#/usr/bin/python manage.py collectstatic --noinput

#other manage.py commands have to run it like 
# python manage.py initgroups

# python manage.py createsuperuserdefault 
# provide arg parse argument with above command
compress_enabled() {
python << END
import sys

from environ import Env

env = Env(COMPRESS_ENABLED=(bool, True))
if env('COMPRESS_ENABLED'):
    sys.exit(0)
else:
    sys.exit(1)

END
}

if compress_enabled; then
  # NOTE this command will fail if django-compressor is disabled
  python /app/manage.py compress
fi
exec /usr/local/bin/gunicorn config.asgi --bind 0.0.0.0:5000 --chdir=/app -k uvicorn.workers.UvicornWorker
